### ISSUE TITLE
你好，Label能支持滚动吗？

### ISSUE THREAD

**Issue by yaonuo** [snail-z/SnailQuickMaskPopups#1]
![111](https://cloud.githubusercontent.com/assets/4479940/23883880/a41cc886-08a4-11e7-926f-f85b42ec0339.png)

如果再支持block弹出，就完美了！

**Comment by snail-z** [comment]
SnailQuickMaskPopups 只负责设置一个蒙版并将自定义的视图弹出，你可以自定义滚动视图，将label放在滚动视图上；
谢谢你建议，后期有时间会进行更新修改。

**Comment by snail-z** [comment]
你说的blcok弹出是指的什么，代理事件写成block么？

**Comment by yaonuo** [comment]
谢谢！期待你的更新。

对的，block是指delegate写成block形式。;-)
